
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export NODE_FMQLADD="https://9100-${GITPOD_WORKSPACE_URL##https://}" && cd compose && docker-compose up

vscode:
  extensions:
    - formulahendry.code-runner
