#
#       AUTHOR - Raman Sailopal
#
#       docker compose yml file for the YottaDB-Dashboard stack
#
version: "2"
services:
 fileman:
   image: docker.io/vistadataproject/nodevista999
   hostname: fileman
   container_name: fileman
   ports:
      - 9330:9430 
      - 32:22 
      - 9100:9000 
      - 9331:8001
      - 8083:8083
      - 8082:8082
   networks:
      - yottanet

 httpd:
   image: docker.io/bitnami/apache
   hostname: httpd
   container_name: httpd
   ports:
      - 8080:8080
   environment:
      - NODE_FMQLADD=$NODE_FMQLADD
   volumes:
      - ../htdocs:/home/htdocs/
      - ../startup:/usr/local/Fileman-d3
   networks:
      - yottanet
   entrypoint: [ "/bin/bash", "-c", "/usr/local/Fileman-d3/start.sh" ]

networks:
    yottanet:
